## To configure your Mkdocs installation using this file,
## refer to Mkdocs documentation

# Basic site config
site_name: The Pins Team English Handbook
site_url: https://en.handbooksbythepins.cf
use_directory_urls: true
theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  logo:
    icon: 'book'
  language: en
docs_dir: handbook

# For translations to the handbook, refer to https://www.mkdocs.org/user-guide/configuration/#lang and https://squidfunk.github.io/mkdocs-material/getting-started/#localization. Must be same as theme language config above. 
lang: en

# Repository information
repo_url: https://gitlab.com/MadeByThePinsTeam-DevLabs/official-handbook-en
repo_name: Fork me on Gitlab.com
edit_uri: blob/master/handbook

# Navigation menu
# Update this as new
nav:
    - 'Introduction': 'index'
    - 'About':
      - 'History of Handbook': 'about'
      - 'Copyright Info': 'copyright'
    - 'The DevOps Cycle':
      - 'Intro to DevOps': 'devops'
    - 'The GitLab Way':
      - 'GitLab What?': 'the-gitlab-way/#gitlab-what'
      - 'Migrating from GitHub': 'the-gitlab-way/movingtogitlab/github'
    - 'Code of Conduct': 'code-of-conduct'
    - 'Life @ The Pins Team':
      - 'Censorship 101':
        - 'Handling Spoilers': 'life-at-the-pins/censorship-101/handling-spoilers'
    - 'In other Languages':
      - 'Fork to localize': "https://gitlab.com/MadeByThePinsTeam-DevLabs/Official-Handbook/-/forks/new"
      - ''

# Markdown extensions and other plugins
# For Markdown extensions for Python, see https://python-markdown.github.io/extensions/ for the full list.
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      provider: gitlab
      user: MadeByThePinsTeam-DevLabs
      repo: official-handbook
      labels: {
        'commit': 'Commit',
        'compare': 'Compare',
        'issue': 'Issue',
        'pull': 'Merge Request',
        'mention': 'GitLab User',
        'repository': 'Repository'
      }
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
    - search
    - git-revision-date-localized:
        type: iso_datetime

# Some extras
extra:
  social:
    - type: 'github'
      link: 'https://github.com/MadeByThePinsHub'
    - type: 'twitter'
      link: 'https://twitter.com/ThePinsTeam'
    - type: 'gitlab'
      link: 'https://gitlab.com/MadeByThePinsTeam-DevLabs'
    - type: 'telegram'
      link: 'https://telegram.dog/ThePinsTeamHub'
